#include "Story.h"
#include <iostream>
using namespace std;

void part1(){
    cout<<"The message said, 'You created this...' Confusion washed over you as you pondered why your malevolent ex-boss would utter such words. As you thought and thought, your inventory system came to mind. But no, that was just for tracking what coffee people drank—surely nothing sinister there. Yet, as you lifted your gaze, a wave of horror struck you. Everyone around was sipping a specific drink provided by CodeBrew. What was in that drink? Memories of a past hack flashed before you. You had breached their system once before; you could do it again. With determined resolve, you logged into the system, only to find everything fragmented, a digital labyrinth meant to thwart intruders. Just then, the leader of CodeBrew appeared once more, smirking as he said, 'Enjoy the treasure hunt.' Glancing down at the chaotic data before you, you realized with a sinking heart that you'd need to crack this twisted treasure hunt to uncover the secrets of the drink. What was CodeBrew really serving? The answer lay hidden, encrypted in the scattered pieces of data you now needed to piece together."<<endl;
}

void part2(){
    cout<<"Macchiato... It dawned on you why that drink was always on your reports as the best-selling item before you were unceremoniously fired. The question that lingered, though, was why were you fired? With these thoughts swirling in your mind, you set to work on the fragmented system, your fingers flying over the keyboard as lines of code started making sense once again. After what felt like hours, the system was finally restored, and amidst the myriad of ordinary files, one stood out ominously: Poison Amount. A chill ran down your spine as you opened it, and the reality hit you—each serving of the macchiato contained a specific poison. This couldn't be an accident. This was deliberate. Panicked yet determined, you began scouring medical databases and toxicology reports, hunting for any information on how to neutralize the poison. Your research paid off. To combat the poison, you needed to precisely calculate the amount of regular coffee required to dilute the toxin to safe levels. The solution seemed straightforward, but the execution would be anything but. You needed to adjust the coffee machines to dispense the correct ratio of coffee to macchiato mix, ensuring every cup poured would be safe to drink. The fate of countless unsuspecting coffee drinkers rested in your hands. Now, it was time to recalibrate and save everyone from the sinister plans of CodeBrew."<<endl;
}

void part3(){
    cout<<"6 cups of coffee—that seemed excessive, but you were confident in your calculations. You updated the system settings to increase the coffee dispensation, counteracting the poison with precision. Your team erupted in celebration, believing you had thwarted CodeBrew's nefarious plans. However, the atmosphere of victory was short-lived. You encountered the so-called leader of CodeBrew once again. This time, he looked defeated, yet his words carried an ominous tone. 'You thought you could stop us with the skills you have... You still have a lot to learn,' he said. Before you could respond, a shocking scene unfolded: everyone who had just enjoyed the coffee collapsed. Frantically, you checked the code you had changed, only to discover a chilling sabotage: someone had altered your update to add six more cups' worth of poison instead of coffee. The 'leader' you had been dealing with wasn't the head of the operation but merely a lower-ranking member of a much larger and more evil corporation. As the gravity of the situation sank in, you realized this was just the beginning of a much longer battle. You prepared yourself for the challenges ahead, knowing that you would need to defeat each leader in this corrupt hierarchy to prevent further harm."<<endl;
    cout<<endl;
    cout<<"You still have a lot to learn, but take each new module and challenge as if it is a build up to a boss and once you know it you have that degree. I believe in yall, now test your code more and good luck with all your exams for the semester." << endl;
}